version: '3.6'

networks:
  nest-blog:

services:
  database:
    container_name: todo-mysql
    image: mysql:8.0.22
    restart: unless-stopped
    ports:
      - '3307:3306'
    volumes:
      - ./docker/db/conf.d/:/etc/mysql/conf.d/
    environment:
      MYSQL_DATABASE: todos
      MYSQL_USER: todo
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Seoul
    networks:
      - nest-blog

  redis:
    container_name: todo-redis
    image: redis
    restart: unless-stopped
    networks:
      - nest-blog
